### ISSUE TITLE
Seems Token is lost

### ISSUE THREAD

**Issue by legantois** [HomeAssistant-Mods/home-assistant-miele#100]
since few days i got the following error. All my config is up to date

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:28
Integration: miele (documentation, issues)
First occurred: 10:00:35 AM (1 occurrences)
Last logged: 10:00:35 AM

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 150, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 47, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 28, in _get_devices_raw
    devices = await self.hass.async_add_executor_job(func)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 496, in request
    token = self.refresh_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant)

**Comment by tomasb82** [comment]
Same for me

**Comment by kloknibor** [comment]
what happens if you remove the token and reboot homeassistant?

**Comment by tomasb82** [comment]
wizard to connect Miele starts

**Comment by kloknibor** [comment]
and if you reconnect everything is ok? This can happen if during the period of time when the component tries to refresh the token it can't due to the system being offline, miele server issues, internet issues etc. The component only refreshes the token when it nearly expires. This could be expected behaviour. 

Nevertheless it might be better to kick of the miele wizard again instead of just throwing an error.

**Comment by legantois** [comment]
My apologies in advance,but could you indicate how to remove the token ? 

Many thanks

**Comment by tomasb82** [comment]
I found it in config/.storage foder. Folder is hiden by defalt

**Comment by legantois** [comment]
Great -

Thanks Tomas

Did it, work back now !

indeed agree with kloknibor that in case of bad auth, could be interesting to ask back the autorisation process

**Comment by kloknibor** [comment]
Please test the new release in the dev branche, you can install it from HACS this should resolve the issue with PR #108
