### ISSUE TITLE
Connection issue since about a month

### ISSUE THREAD

**Issue by tbaumann** [HomeAssistant-Mods/home-assistant-miele#101]
I get this error at startup. It used to work fine before that. I'm pretty sure I changed nothing except HA updates.

```
Logger: homeassistant.setup
Source: helpers/network.py:122
First occurred: 15:42:52 (1 occurrences)
Last logged: 15:42:52

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 123, in async_setup
    network.get_url(hass, allow_external=True, prefer_external=True),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 122, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

**Comment by tbaumann** [comment]
Oh fascinating. I fixed it.

The NabuCasa account was expired. I suspect the ` prefer_external=True` parameter might have something to do with that.
