### ISSUE TITLE
Binary Sensor Error: Task exception was never retrieved 

### ISSUE THREAD

**Issue by FransHalsjes** [HomeAssistant-Mods/home-assistant-miele#102]
Since 2021.12.10 the miele integration keeps giving:

```
Logger: homeassistant
Source: custom_components/miele/binary_sensor.py:88
Integration: Miele@home (documentation, issues)
First occurred: 31 januari 2022 13:28:26 (8188 occurrences)
Last logged: 06:50:39

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 205, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'

'''

**Comment by mhageraats** [comment]
Same here (now on 2022.4.1)

> 2022-04-08 10:50:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
> state = self._stringify_state(available)
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
> if (state := self.state) is None:
> File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
> if (is_on := self.is_on) is None:
> File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
> return bool(self._device["state"][self._key])
> KeyError: 'signalInfo'
> 2022-04-08 10:50:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
> state = self._stringify_state(available)
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
> if (state := self.state) is None:
> File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
> if (is_on := self.is_on) is None:
> File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
> return bool(self._device["state"][self._key])
> KeyError: 'signalFailure'
> 2022-04-08 10:50:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
> state = self._stringify_state(available)
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
> if (state := self.state) is None:
> File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
> if (is_on := self.is_on) is None:
> File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
> return bool(self._device["state"][self._key])
> KeyError: 'signalDoor'

**Comment by baferdi** [comment]
Same Issue...

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/miele/sensor.py:725
Integration: Miele@home (documentation, issues)
First occurred: 19:41:08 (16 occurrences)
Last logged: 19:41:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 725, in state
    state_value = self._device["state"][self._key][self._index]["value_raw"]
IndexError: list index out of range

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/miele/binary_sensor.py:88
Integration: Miele@home (documentation, issues)
First occurred: 19:41:08 (16 occurrences)
Last logged: 19:41:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'
