### ISSUE TITLE
Not connecting(solved)

### ISSUE THREAD

**Issue by mini89** [HomeAssistant-Mods/home-assistant-miele#109]
After i update home assistant to 2022.3.6 the miele is not working anymore.

I tried to;
- reinstall HACS
- reinstall Miele
- get new token

And every time i restart i get the same error:

Logger: homeassistant.setup
Source: helpers/network.py:172
First occurred: 07:11:32 (1 occurrences)
Last logged: 07:11:32

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 123, in async_setup
    network.get_url(hass, allow_external=True, prefer_external=True),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 133, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 172, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by mini89** [comment]
Change the web settings
