### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by vicfalls** [HomeAssistant-Mods/home-assistant-miele#113]
hi guys,

since I installed "duckdns" and "let's encrypt" (now it runs via a https protocol) I get following message:

      The following integrations and platforms could not be set up:
      
      [miele](https://github.com/HomeAssistant-Mods/home-assistant-miele)
      Please check your config and [logs](https://xxxxxxxxxxxxxxxxx/config/logs).

the log says following:

    Logger: homeassistant.setup
    Source: helpers/network.py:207 
    First occurred: 15:17:29 (1 occurrences) 
    Last logged: 15:17:29
    
    Error during setup of component miele
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
        result = await task
      File "/config/custom_components/miele/__init__.py", line 124, in async_setup
        network.get_url(hass, allow_external=True, prefer_external=True),
      File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 168, in get_url
        request_host = _get_request_host()
      File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 207, in _get_request_host
        raise NoURLAvailableError
    homeassistant.helpers.network.NoURLAvailableError

pls. let me know, what I need to do, to get it running again.
Thanks a lot
Vic

**Comment by kloknibor** [comment]
You need to set your external URL correctly see other closed issues
