### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by piechade** [HomeAssistant-Mods/home-assistant-miele#114]
I'm getting this warning on start.
````
RuntimeWarning: coroutine 'MieleOAuth.refresh_token' was never awaited
````

Today I'm getting 

````
Failed to retrieve Miele devices: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
````

**Comment by kloknibor** [comment]
Does the integration still work or not at all? Did it use to work?

**Comment by piechade** [comment]
The integration works perfectly. The only thing is that it shows Water consumption what is not working.

**Comment by KennethLavrsen** [comment]
I also see RuntimeWarning: coroutine 'MieleOAuth.refresh_token' was never awaited
  self.refresh_token(hass)
It it shown once when you restart HA. I have no other issues at runtime. Only seen at boot

**Comment by florie1706** [comment]
During startup of HA 2022.07 I get a similar error. Is it possible to "fix" this?

```
/config/custom_components/miele/miele_at_home.py:138: RuntimeWarning: coroutine 'MieleOAuth.refresh_token' was never awaited
  self.refresh_token(hass)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2022-07-09 07:05:51 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2022-07-09 07:05:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up miele platform for sensor
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/miele/sensor.py", line 354, in setup_platform
    if "status" in device_state and state_capability(
  File "/config/custom_components/miele/sensor.py", line 327, in state_capability
    if state in capabilities[type_str]:
KeyError: '74'
```

**Comment by Giolovin** [comment]
same issue here:
2023-01-12 14:16:54.020 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration miele which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-12 14:17:08.805 WARNING (MainThread) [py.warnings] /config/custom_components/miele/miele_at_home.py:138: RuntimeWarning: coroutine 'MieleOAuth.refresh_token' was never awaited
2023-01-12 14:17:09.740 ERROR (MainThread) [homeassistant.setup] Error during setup of component miele
File "/config/custom_components/miele/__init__.py", line 152, in async_setup
File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
File "/config/custom_components/miele/miele_at_home.py", line 32, in _get_devices_raw
File "/config/custom_components/miele/miele_at_home.py", line 165, in refresh_token
File "/config/custom_components/miele/miele_at_home.py", line 174, in sync_refresh_token

Has anyone been able to fix this issue?
