### ISSUE TITLE
Integration fails to start in 2022.6.7

### ISSUE THREAD

**Issue by KennethLavrsen** [HomeAssistant-Mods/home-assistant-miele#117]
After upgrading HA to 2022.6.7 the component fails to load with this error

```
2022-06-22 16:22:52 ERROR (MainThread) [homeassistant.setup] Error during setup of component miele
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/miele/__init__.py", line 153, in async_setup
hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
File "/config/custom_components/miele/__init__.py", line 109, in _to_dict
for item in items:
TypeError: 'NoneType' object is not iterable
```

**Comment by neildsb** [comment]
+1

Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:174
Integration: miele (documentation, issues)
First occurred: 3:48:09 pm (1 occurrences)
Last logged: 3:48:09 pm

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 152, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 32, in _get_devices_raw
    if await self._session.refresh_token(self.hass):
  File "/config/custom_components/miele/miele_at_home.py", line 165, in refresh_token
    self._token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/miele/miele_at_home.py", line 174, in sync_refresh_token
    return self._session.refresh_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 451, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

**Comment by VChrissiERM** [comment]
Hi,

same here.

Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:29
Integration: miele ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues))
First occurred: 23:09:19 (1 occurrences)
Last logged: 23:09:19

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 152, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 29, in _get_devices_raw
    devices = await self.hass.async_add_executor_job(func)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 502, in request
    token = self.refresh_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant)

**Comment by sdt-ryan** [comment]
I can't even log into their swagger online so it seems like maybe something is broken on Mieles end... After inputting client_id and client_secret I get redirected to a basic auth login page where I use the same creds that I used in the mobile app and it always rejects with auth failed...

https://www.miele.com/developer/swagger-ui/swagger.html

**Comment by azeroth12** [comment]
I can't even log into their swagger online so it seems like maybe something is broken on Mieles end... After inputting client_id and client_secret I get redirected to a basic auth login page where I use the same creds that I used in the mobile app and it always rejects with auth failed...

https://www.miele.com/developer/swagger-ui/swagger.html

**Comment by KennethLavrsen** [comment]
The developer has not done anything on the project for 3 months and the current state is that it does not work at all.

Anyone waiting or seeing this now - change to the similar project https://github.com/astrandb/miele

That newer project is well maintained and works great with a few extra features.

I say this not to be grumpy against the author but to help fellow users. I want to thank for the time this project was of good use to me.
