### ISSUE TITLE
Add support for KMDA 7476 FR

### ISSUE THREAD

**Issue by Adi146** [HomeAssistant-Mods/home-assistant-miele#125]
I'm trying to add my miele cooktop to home assistant using your custom component. When I start my Home Assistant I only see one entity named `miele.miele_000176361536` and an error logged. It would be nice to have full support for this device too. The full product ID is `KMDA 7476 FR`

```
Logger: homeassistant.components.sensor
Source: custom_components/miele/sensor.py:327
Integration: Sensor (documentation, issues)
First occurred: 21. August 2022 um 19:07:56 (1 occurrences)
Last logged: 21. August 2022 um 19:07:56

Error while setting up miele platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/miele/sensor.py", line 354, in setup_platform
    if "status" in device_state and state_capability(
  File "/config/custom_components/miele/sensor.py", line 327, in state_capability
    if state in capabilities[type_str]:
KeyError: '74'
```

**Comment by Adi146** [comment]
It seems like there aren't even docs for this device, so we will probably have to wait for this.
