### ISSUE TITLE
Cannot see integration - no errors

### ISSUE THREAD

**Issue by Maxwell2022** [HomeAssistant-Mods/home-assistant-miele#146]
I'm using HA in supervised mode and installed Miele with HACS (note there are 2 integrations with the same name in HACS). 

Following the instruction, I first update my `configuration.yaml` adding the `miele` configuration section but it refused to restart HA because of an invalid configuration (miele platform does not exist). I had to comment it out, restart HA and uncomment the configuration again then restart again.

I cannot see the integration, if I go to add integration, I see the Miele one but it says that it can only be added by configuration (which I've done). I have no errors in the logs. Not sure what I missed.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/670701/224459319-ff9b1cf3-324f-45de-a583-15d5892135b8.png">

`/config/configuration.yaml`
<img width="520" alt="image" src="https://user-images.githubusercontent.com/670701/224459389-cb59085f-f312-40eb-a7ec-6cf5772760fa.png">

**Comment by fpauser** [comment]
same here

**Comment by GDCAU** [comment]
Im not sure at what point mine stopped working. Im thinking mid Feb.

Noticed this in the logs. Ive refreshed the token on the Miele developer site, but still not working.

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 152, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 48, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 29, in _get_devices_raw
    devices = await self.hass.async_add_executor_job(func)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 502, in request
    token = self.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant)

**Comment by Maxwell2022** [comment]
> TokenExpiredError

you probably need to generate a new token 🤷‍♂️

**Comment by GDCAU** [comment]
> you probably need to generate a new token 🤷‍♂️

Yes as I mentioned above ive grabbed a new token from the Miele developer portal but its still generating the errors.

**Comment by dongennl** [comment]
My situation is similar to @Maxwell2022 ; I'm running HA on Docker, but with a volume mapped for config, so it persists; I followed the manual installation instructions to the letter and have my brand new tokens from Miele.
Rebooting HA after config I don't see any UI (where are we supposed to see this??), I can go to add Integration and see the Miele integration, but same errors as Maxwell (You cannot add via UI, etc.).

Looking at logs no errors at all and the Miele integration seems to be loaded:
`2023-03-21 10:24:53.563 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-21 10:24:53.564 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration miele which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

(for comparison Node Red is also manually installed and works perfectly). I'm not sure what to do...

**Comment by dongennl** [comment]
I deleted this one and went with https://github.com/astrandb/miele ; worked perfectly first time; no messing with YAML.

**Comment by defux-23** [comment]
> I cannot see the integration, if I go to add integration, I see the Miele one but it says that it can only be added by configuration (which I've done). I have no errors in the logs. Not sure what I missed.

I had a similar issue (seeing the Integration in search, but could not add/configure it), maybe my second post here helps:
https://github.com/HomeAssistant-Mods/home-assistant-miele/issues/149#issuecomment-1500646587

**Comment by Maxwell2022** [comment]
I just ended up using https://github.com/astrandb/miele - Works like a charm first try
