### ISSUE TITLE
Error during setup of component Miele

### ISSUE THREAD

**Issue by MathieuWuyts** [HomeAssistant-Mods/home-assistant-miele#154]
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:109 
Integration: miele (documentation, issues) 
First occurred: 20:38:52 (1 occurrences) 
Last logged: 20:38:52

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 153, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
  File "/config/custom_components/miele/__init__.py", line 109, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

**Comment by dadek16** [comment]
Same here. After hassio update to latest version

**Comment by kurtSejr** [comment]
Updated both Miele integration and HA 2023.5, result in this error:

Logdetaljer (FEJL)
Denne fejl stammer fra en brugerdefineret integration.
Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:127
Integration: miele ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues))
First occurred: 17.48.32 (1 occurrences)
Last logged: 17.48.32

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 127, in async_setup
    cache = config[DOMAIN].get(
KeyError: 'miele'

**Comment by DIJONNL** [comment]
Same here. Since the last update, suddenly a Miele keyerror! Any solution to solve the issue?

**Comment by SolutionHacker** [comment]
Same here - on upgrade from 2023.4.x to 2023.5.2.   Slightly different presentation of error message in logs

Logger: homeassistant.setup
Source: setup.py:348
First occurred: 4:16:52 PM (1 occurrences)
Last logged: 4:16:52 PM

Unable to prepare setup for platform miele.sensor: Platform not found (cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)).

2023-05-13 16:16:52.442 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform miele.sensor: Platform not found (cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)).

**Comment by kloknibor** [comment]
I think you all need to update to the latest version with HACS, this issue should be resolved in the latest version. async_get_registry is no longer used in the newest version of this component.

**Comment by SolutionHacker** [comment]
Thank you Robin!   I missed that and after updating all fixed!
