### ISSUE TITLE
core update 2023.5.4

### ISSUE THREAD

**Issue by Koosdezwart** [HomeAssistant-Mods/home-assistant-miele#156]
after core update:

Home Assistant Core
Unable to prepare setup for platform miele.sensor: Platform not found (Exception importing custom_components.miele.sensor).
06:22:56 – (FOUT) setup.py
Unexpected exception importing platform custom_components.miele.sensor
06:22:56 – (FOUT) loader.py

Home Assistant Core
2023-05-25 06:22:56.343 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.miele.sensor
2023-05-25 06:22:56.347 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform miele.sensor: Platform not found (Exception importing custom_components.miele.sensor).

**Comment by pierrejo** [comment]
Same thing for me :
```
Logger: homeassistant.setup
Source: setup.py:348
First occurred: 10:54:37 (1 occurrences)
Last logged: 10:54:37

Unable to prepare setup for platform miele.sensor: Platform not found (Exception importing custom_components.miele.sensor).
```

and :
```
Unexpected exception importing platform custom_components.miele.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/miele/sensor.py", line 5
    from homeassistant.const import SensorDeviceClass.ENERGY
                                                     ^
SyntaxError: invalid syntax
```


---
My configuration :
- Home Assistant 2023.5.4
- Supervisor 2023.04.1
- Operating System 10.1
- Interface utilisateur : 20230503.3 - latest
- Hardware : Raspberry Pi 4

**Comment by pille89** [comment]
Hi all I have the same problem with exactly the same error message

**Comment by tvanhove** [comment]
Same here!

**Comment by pille89** [comment]
the problem is temporarily fixed by re-downloading with version 0.9.4 and then do not upgrade to 0.9.5.

**Comment by kloknibor** [comment]
Please try the new update that was just released, this should solve it :-)

**Comment by pille89** [comment]
Thanks that works
