### ISSUE TITLE
Unexpected exception importing platform custom_components.miele.sensor

### ISSUE THREAD

**Issue by MicroZot** [HomeAssistant-Mods/home-assistant-miele#157]
HI,
I have a Miele 7130 dishwasher.
In recent months, the integration worked. Then due to a malfunction I deleted (even the token from the .storage folder), and reinstalled everything.
integration:  miele-0.9.5
Home assistant: 2023.5.4

Now I can't get the integration to work anymore. I recreated the token but I get the following error messages:

------------
Logger: homeassistant.loader
Source: loader.py:850
First occurred: 17:01:16 (1 occurrences)
Last logged: 17:01:16

Unexpected exception importing platform custom_components.miele.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/miele/sensor.py", line 5
    from homeassistant.const import SensorDeviceClass.ENERGY
                                                     ^
SyntaxError: invalid syntax
---------------------------
Logger: homeassistant.setup
Source: setup.py:348
First occurred: 17:01:16 (1 occurrences)
Last logged: 17:01:16

Unable to prepare setup for platform miele.sensor: Platform not found (Exception importing custom_components.miele.
------

Suggestions?
Thank you
Andrew C

**Comment by kloknibor** [comment]
Please try the new update that was just released, this should solve it :-)
