### ISSUE TITLE
Issues with latest update HA 2023.7.2

### ISSUE THREAD

**Issue by apedance** [HomeAssistant-Mods/home-assistant-miele#162]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:383
Integration: miele (documentation, issues)
First occurred: 11:49:56 (1 occurrences)
Last logged: 11:49:56

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 427, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 383, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/miele/miele_at_home.py:177
Integration: miele (documentation, issues)
First occurred: 11:46:55 (1 occurrences)
Last logged: 11:46:55

/config/custom_components/miele/miele_at_home.py:177: RuntimeWarning: coroutine 'MieleOAuth.refresh_token' was never awaited self.refresh_token(hass)

**Comment by x3style** [comment]
I have something similar i think if not the same.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:383
Integration: miele ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues))
First occurred: 2:33:30 PM (1 occurrences)
Last logged: 2:33:30 PM

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 427, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 383, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

**Comment by troinine** [comment]
I did try reverting back to 2023.7.1 but the problem is still present. 

Further investigation indicates that this appears to be an issue with Miele 3rd party API (https://api.mcs3.miele.com/v1/). The problem started roughly 9:15 UTC today. The 3rd party API seems to be not responding at all.

No indication of changes in https://www.miele.com/developer/news.html that might have caused this.

**Comment by Morteum9** [comment]
I've actually been meaning to write something up on this, I noticed it when I updated to 23.7.0 earlier this month. Been taking later 7.x updates hoping it would clear it up but more signs were pointing to Miele itself since then.

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:383
Integration: miele (documentation, issues)
First occurred: July 13, 2023 at 8:14:51 PM (1 occurrences)
Last logged: July 13, 2023 at 8:14:51 PM

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 427, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 383, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

**Comment by TomStarren** [comment]
So I also had this issue but for me the following steps fixed the issue.

- Register again with Miele (https://www.miele.com/f/com/en/register_api.aspx)
- Remove the file in HA which contains the tokens
- Reboot
- Reauthenticate the Miele integration
- Reboot

**Comment by Morteum9** [comment]
> So I also had this issue but for me the following steps fixed the issue.
> 
> * Register again with Miele (https://www.miele.com/f/com/en/register_api.aspx)
> * Remove the file in HA which contains the tokens
> * Reboot
> * Reauthenticate the Miele integration
> * Reboot

Still getting the same error after these steps

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:383
Integration: Miele@home (documentation, issues)
First occurred: 4:37:56 PM (1 occurrences)
Last logged: 4:37:56 PM

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 427, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 383, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable

**Comment by Lmhog** [comment]
> So I also had this issue but for me the following steps fixed the issue.
> 
> * Register again with Miele (https://www.miele.com/f/com/en/register_api.aspx)
> * Remove the file in HA which contains the tokens
> * Reboot
> * Reauthenticate the Miele integration
> * Reboot

I'm sorry, but i'm new in HA.
How do you remove Miele token files i HA?

**Comment by martingruening** [comment]
The same things happens here. Functionality stopped yesterday. Re-registering didn't help. Any thoughts?

**Comment by pille89** [comment]
Same problem.....

**Comment by faibe24** [comment]
Same here, even on clean installation

**Comment by jamesmccarthy** [comment]
If you're having this issue, can you please comment on whether you have IPv6 (and an address) for your HASS instance?

If so, please try disabling IPv6. 

Edit: Don't pursue this necessarily. Was causing the issue for me for both Miele and other add-ons after upgrading to 23.7.3, but may be unrelated for Miele.

**Comment by martingruening** [comment]
> If you're having this issue, can you please comment on whether you have IPv6 (and an address) for your HASS instance?

No, I had troubles with IPv6 + HASS before. Therefore I have connected Home Assistant to an IPv4-only network in Docker (this solved all the previous IPv6 troubles).

**Comment by haukekiesswetter** [comment]
Same here .. just tried to do a first install & activate .. no ipv6 / no success

**Comment by pille89** [comment]
Is there a solution?

**Comment by haukekiesswetter** [comment]
> Is there a solution?

Well i switched to the other miele integration : https://github.com/astrandb/miele this one seems to work (at least for me)
