### ISSUE TITLE
Integration not loading in 2024.10.1

### ISSUE THREAD

**Issue by FrankSchoene** [HomeAssistant-Mods/home-assistant-miele#176]
Logger: homeassistant.setup
Quelle: setup.py:416
Erstmals aufgetreten: 20:55:16 (1 Vorkommnisse)
Zuletzt protokolliert: 20:55:16

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 401, in async_setup
    cache = config[DOMAIN].get(
            ~~~~~~^^^^^^^^
KeyError: 'miele'

**Comment by yvansandoz** [comment]
Same for me.

**Comment by khv123** [comment]
same here

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 422, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 401, in async_setup
    cache = config[DOMAIN].get(
            ~~~~~~^^^^^^^^

**Comment by MrStrathmore** [comment]
Getting same error

Logger: homeassistant.setup
Source: setup.py:422
First occurred: 12:04:03 (1 occurrences)
Last logged: 12:04:03

Error during setup of component miele: 'miele'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 422, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 401, in async_setup
    cache = config[DOMAIN].get(
            ~~~~~~^^^^^^^^
KeyError: 'miele'

**Comment by lysanev** [comment]
same error 

Error during setup of component miele: 'miele'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 422, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 401, in async_setup
    cache = config[DOMAIN].get(
            ~~~~~~^^^^^^^^
KeyError: 'miele'
