### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nagyrobi** [HomeAssistant-Mods/home-assistant-miele#30]
Great component, thank you!

When there's any internet connection problem, the log of Home Assistant starts to fill with task exceptions.
I am not using debug mode. It should be handled to mute these kinds of errors from the log, one single informative line would be enough, something like "timed out connecting to miele servers"

```
2021-03-12 19:46:04 ERROR (MainThread) [custom_components.miele.miele_at_home] Failed to retrieve Miele devices: HTTPSConnectionPool(host='api.mcs3.miele.com', port=443): Max retries exceeded with url: /v1/devices?language=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4f1ac80ac0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
2021-03-12 19:46:04 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-03-12 19:46:08 ERROR (MainThread) [custom_components.miele.miele_at_home] Failed to retrieve Miele devices: HTTPSConnectionPool(host='api.mcs3.miele.com', port=443): Max retries exceeded with url: /v1/devices?language=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4f1a67f730>: Failed to establish a new connection: [Errno 110] Operation timed out'))
2021-03-12 19:46:08 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-03-12 20:00:16 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 353, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.mcs3.miele.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/miele/__init__.py", line 161, in refresh_devices
    device_state = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 47, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 28, in _get_devices_raw
    devices = await self.hass.async_add_executor_job(func)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.mcs3.miele.com', port=443): Read timed out. (read timeout=None)
```

**Comment by kloknibor** [comment]
hi @nagyrobi you are correct that it would be a cleaner error to just say hey we can't connect  to miele. This error will show up every 5 seconds at the moment though, but you won't have such a big error anymore. I will change it in the next release!

**Comment by nagyrobi** [comment]
Thanks

**Comment by gigatexel** [comment]
Is there a reason this error occurs once every day, even when no issues are detected on internet/wifi side?

**Comment by nagyrobi** [comment]
Maybe there's a maintenance on the Miele server side at those moments.
