### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by gigatexel** [HomeAssistant-Mods/home-assistant-miele#31]
When our washing machine is started/running, this warning occurs.
Seems to be related to async:

```Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for miele doing I/O at custom_components/miele/miele_at_home.py, line 71```

**Comment by gigatexel** [comment]
Updated but not fixed, unfortunately

`Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for miele doing I/O at custom_components/miele/miele_at_home.py, line 71: result = await self._session._session.put(`

but also:

```
[2775370984] object Response can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/miele/__init__.py", line 210, in _action_service
    await _apply_service(service, MieleDevice.action, body)
  File "/config/custom_components/miele/__init__.py", line 205, in _apply_service
    await service_func(device, *service_func_args)
  File "/config/custom_components/miele/__init__.py", line 331, in action
    await self._client.action(self.unique_id, action)
  File "/config/custom_components/miele/miele_at_home.py", line 71, in action
    result = await self._session._session.put(
TypeError: object Response can't be used in 'await' expression
```

**Comment by gigatexel** [comment]
Unfortunately, not actually fixed with new version:

![image](https://user-images.githubusercontent.com/65073191/115524000-f33ece00-a28d-11eb-859f-8336804cb5cd.png)

**Comment by kloknibor** [comment]
#49 does resolve this issue, thanks for your contribution!
