### ISSUE TITLE
Still error during setup of component miele after deleting cache token.

### ISSUE THREAD

**Issue by ergodia** [HomeAssistant-Mods/home-assistant-miele#35]
Hi, I can't seem to get the integration working. I have deleted the .miele-token-cache but I don't get a pup-up to set everything up again. Any advise? Thanks.

Error during setup of component miele
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/home/homeassistant/.homeassistant/custom_components/miele/__init__.py", line 120, in async_setup
    callback_url = "{}{}".format(get_url(hass), AUTH_CALLBACK_PATH)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/network.py", line 84, in get_url
    request_host = _get_request_host()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/network.py", line 124, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by mhaack** [comment]
Same here, after HA 2021.4 upgrade the Miele integrate stopped working, deleted the .. token. The re-setup does not work anymore. Tried to link my Miele account, after auth on the Miele site the redirect to HA results in 500 error and the following log:

```
2021-04-08 15:45:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 128, in handle
    result = handler(request, **request.match_info)
  File "/config/custom_components/miele/__init__.py", line 241, in get
    result = self.oauth.get_access_token(request.query["code"])
  File "/config/custom_components/miele/miele_at_home.py", line 141, in get_access_token
    token = self._session.fetch_token(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 336, in fetch_token
    r = self.request(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/miele/miele_at_home.py, line 141: token = self._session.fetch_token(
```
