### ISSUE TITLE
Error during setup of component miele with Home Assistant 2021.4.x

### ISSUE THREAD

**Issue by riccmike** [HomeAssistant-Mods/home-assistant-miele#37]
When I update to 2021.4.x my Home Assistant , the Miele integration not work, this is the error log:

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:52
First occurred: 6:51:41 (1 occurrences)
Last logged: 6:51:41

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 240, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 145, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 52, in get_devices
    for home_device in home_devices:
TypeError: 'coroutine' object is not iterable

**Comment by nagyrobi** [comment]
I get hundreds of this:

```
2021-04-09 11:22:25 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:22:46 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:25:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:25:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:25:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:25:47 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:25:52 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:25:57 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:02 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:07 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:12 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:17 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:22 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:47 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:52 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:26:57 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:03 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:07 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:12 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:17 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:22 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:47 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:52 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:27:57 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:02 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:07 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:12 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:17 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:22 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:47 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:53 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:28:57 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:03 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:07 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:13 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:23 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:29 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:33 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:38 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:49 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:29:53 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:05 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:07 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:08 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:12 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:13 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:14 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:17 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:17 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:18 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:22 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:23 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:23 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:24 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:27 WARNING (SyncWorker_23) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:28 WARNING (SyncWorker_29) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:28 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:29 WARNING (SyncWorker_39) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:29 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:32 WARNING (SyncWorker_25) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:33 WARNING (SyncWorker_42) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:33 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:34 WARNING (SyncWorker_31) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:34 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:37 WARNING (SyncWorker_46) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:38 WARNING (SyncWorker_53) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:38 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:39 WARNING (SyncWorker_6) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:39 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:42 WARNING (SyncWorker_54) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:43 WARNING (SyncWorker_13) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:43 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:43 WARNING (SyncWorker_58) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:43 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:47 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:48 WARNING (SyncWorker_15) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:48 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:48 WARNING (SyncWorker_4) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:48 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:49 WARNING (SyncWorker_57) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:49 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:52 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:53 WARNING (SyncWorker_20) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:53 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:54 WARNING (SyncWorker_59) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:54 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:57 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:58 WARNING (SyncWorker_9) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:58 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:30:58 WARNING (SyncWorker_38) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:30:58 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:02 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:03 WARNING (SyncWorker_50) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:31:03 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:07 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:12 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:22 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:35 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:37 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:42 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:47 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:31:52 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:32:52 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:35:09 WARNING (SyncWorker_27) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:35:10 WARNING (SyncWorker_21) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:35:20 WARNING (SyncWorker_16) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:35:20 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:35:56 WARNING (SyncWorker_5) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:36:05 WARNING (SyncWorker_0) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:36:09 WARNING (SyncWorker_13) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
2021-04-09 11:36:09 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:36:12 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:36:17 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:36:23 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:36:27 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:36:32 ERROR (MainThread) [custom_components.miele] Did not receive Miele devices
2021-04-09 11:36:45 WARNING (SyncWorker_30) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
```

**Comment by nagyrobi** [comment]
We need some kind of offline solution. Would be better not to rely on cloud, while HA and the Miele devices reside actually in the same network...

**Comment by kloknibor** [comment]
@nagyrobi would be very helpfull but not possible from Miele's side. If you want to see this future you will need to request this with miele. Currently only a limited online API is available for us. 

The error you see at the start means that Miele returns an empty response so either your account is not set-up properly or you have no acces to the Miele server. Not something I can fix on my end sorry! To test if it is your account please connect with your account here and see if the API works: https://www.miele.com/developer/swagger-ui/swagger.html
