### ISSUE TITLE
Error while changing light

### ISSUE THREAD

**Issue by Anonymoesje** [HomeAssistant-Mods/home-assistant-miele#44]
When trying to change the light of a Miele cooker hood this error occurs:

```
Error executing service: <ServiceCall miele.action (c:): device_id=000xxxxxxxx, body=light=2>
Error executing service: <ServiceCall miele.action (c: device_id=000xxxxxxxxx, body=light=1>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1496, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/miele/__init__.py", line 211, in _action_service
    await _apply_service(service, MieleDevice.action, body)
  File "/config/custom_components/miele/__init__.py", line 206, in _apply_service
    await service_func(device, *service_func_args)
  File "/config/custom_components/miele/__init__.py", line 336, in action
    await self._client.action(self.unique_id, action)
  File "/config/custom_components/miele/miele_at_home.py", line 71, in action
    result = await self._session._session.put(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 602, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/miele/miele_at_home.py, line 71: result = await self._session._session.put(
```

**Comment by luca1982d** [comment]
Hi,

now the light works well, but there is the same problem with the ventilation fan

2021-04-19 15:00:17 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 285, in async_update_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Cooker hood


Could you please fix also this problem?

Thanks
Luca

**Comment by kloknibor** [comment]
Original issue has been resolved with @sebva 's fix, thanks for your contribution :-)!
