### ISSUE TITLE
Still Error during setup of component miele

### ISSUE THREAD

**Issue by ergodia** [HomeAssistant-Mods/home-assistant-miele#53]
Hi,

A while ago I made an issue with the exact same problem. I have seen that it should be solved, so I updated it but I still can't get it to work. I have a feeling that I'm doing something wrong. Does anyone have any advice for me to get it working? Many thanks.

Logger: homeassistant.setup
Source: helpers/network.py:123
First occurred: 15:55:24 (1 occurrences)
Last logged: 15:55:24

Error during setup of component miele
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/home/homeassistant/.homeassistant/custom_components/miele/__init__.py", line 121, in async_setup
    callback_url = "{}{}".format(get_url(hass), AUTH_CALLBACK_PATH)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/network.py", line 123, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by kloknibor** [comment]
you found the solution since you closed the issue yourself already? what was wrong?

**Comment by ergodia** [comment]
Well I was searching for a solution for another problem which stated that I had to fill in the external URL, which I use. It didn't solve the problem where I was looking for but it saved this problem. Now I can use it again.
