### ISSUE TITLE
After HA update Miele token_expired

### ISSUE THREAD

**Issue by stefferber** [HomeAssistant-Mods/home-assistant-miele#55]
Hello,

after my update from core 2021.5.5 -> 2021.7.4 my Miele integration has trouble. 
* re-installed miele integration via HACS
* created new Miele Client ID	and Client Secret, working fine in the [Miele swagger](https://www.miele.com/developer/swagger-ui/index.html)

But I still get his error message:
```

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:28
Integration: miele (documentation, issues)
First occurred: 15:21:52 (1 occurrences)
Last logged: 15:21:52

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 146, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 47, in get_devices
    home_devices = await self._get_devices_raw(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 28, in _get_devices_raw
    devices = await self.hass.async_add_executor_job(func)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 496, in request
    token = self.refresh_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 435, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```
Any hints what this is about?

**Comment by mini89** [comment]
In de file editor of your HA there is a file config/.miele-token-cache. Remove the file en then reboot your HA en it will ask to login again

**Comment by kloknibor** [comment]
@stefferber did you resolve this? If not you could also try the dev repo. It has a change in location of the token, maybe that helpes (will require you to login)

**Comment by stefferber** [comment]
Thx @mini89 ! your hint worked out fine. I was not aware of a breaking change with the Miele integration. Looks like I missed this in the change log file.

**Comment by dolodobendan** [comment]
> In de file editor of your HA there is a file config/.miele-token-cache. Remove the file en then reboot your HA en it will ask to login again

Mental note:

Now it's /config/.storage/.miele-token-cache

**Comment by stefferber** [comment]
Thx for mental note ;-)
