### ISSUE TITLE
Won't set up correctly when using DuckDNS

### ISSUE THREAD

**Issue by DrBlackRat** [HomeAssistant-Mods/home-assistant-miele#65]
So, when I try to use the Miele integration it won't work and I get the error down below. I'm still new to HA so I would appreciate some help to get this solved.

```Logger: homeassistant.setup
Source: helpers/network.py:123
First occurred: 22:33:24 (1 occurrences)
Last logged: 22:33:24

Error during setup of component miele

Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component

    result = await task
  File "/config/custom_components/miele/__init__.py", line 121, in async_setup
    callback_url = "{}{}".format(get_url(hass), AUTH_CALLBACK_PATH)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 123, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError```

**Comment by DrBlackRat** [comment]
So, this seems to be caused by using DuckDNS for the external connection.

**Comment by dreiekk** [comment]
Sadly, it's the same for me using the Let's Encrypt addon out of the box.

Explicitly setting the `internal_url` and `external_url` in my `configuration.yaml` fixed it for me:

```yaml
homeassistant:
  internal_url: "https://192.168.2.100:8123"
  external_url: "https://example.duckdns.org:8123"
```

**Comment by kloknibor** [comment]
#62 Will fix this issue, when I got time will check this PR out and merge to dev

**Comment by kloknibor** [comment]
This should be solved in the last release
