### ISSUE TITLE
"TypeError: argument of type 'NoneType' is not iterable" in ecoFeedback sensor

### ISSUE THREAD

**Issue by mundschenk-at** [HomeAssistant-Mods/home-assistant-miele#79]
Since the last update, I get the following error repeating in the logs with my `G6865-W` dishwasher:

```
2021-11-01 10:35:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 443, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 462, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 657, in state
    if "currentWaterConsumption" in device_state["ecoFeedback"]:
TypeError: argument of type 'NoneType' is not iterable
```

If I remember correctly, the Miele API does not support ecoFeedback for my device.

**Comment by kloknibor** [comment]
Hi! 

thanks for your bug report. The integration should only make ecofeedback sensors when miele returns API information about it so this shouldn't happen. I will look into this, thanks!

**Comment by mundschenk-at** [comment]
Anything I can do to help?

**Comment by mundschenk-at** [comment]
I've checked this with swagger: Apparently even unsupported devices no get the `ecoFeedback` key in their state data, with `None` of course. The capabilities check would need to have knowledge about specific devices to differentiate things there.

**Comment by kloknibor** [comment]
Merged PR into dev, please test if this solves your issue :-)
