### ISSUE TITLE
Task exception was not retrieved

### ISSUE THREAD

**Issue by gigatexel** [HomeAssistant-Mods/home-assistant-miele#86]
I have constant "task exception was never retrieved" errors unfortunately.
Is a washing machine that is turned off.

```
Logger: homeassistant
Source: custom_components/miele/binary_sensor.py:88
Integration: Miele@home (documentation, issues)
First occurred: December 16, 2021, 18:22:53 (32849 occurrences)
Last logged: 11:24:30

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 205, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'
```

**Comment by eikowagenknecht** [comment]
Same here, I have thousands of those:

![image](https://user-images.githubusercontent.com/1475672/148664736-b59da710-93ec-410f-b934-227d4bd9abf6.png)

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 644, in state
    if "currentEnergyConsumption" in device_state["ecoFeedback"]:
TypeError: argument of type 'NoneType' is not iterable
```

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/miele/sensor.py", line 657, in state
    if "currentWaterConsumption" in device_state["ecoFeedback"]:
TypeError: argument of type 'NoneType' is not iterable
```

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 205, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'
```

**Comment by N3rdix** [comment]
Same issue in my side, the logs let my disk space constantly shrink…

**Comment by kloknibor** [comment]
Could you guys see if the latest beta release solves your issue?

**Comment by eikowagenknecht** [comment]
> Could you guys see if the latest beta release solves your issue?

Thank you, just installied it, will report in a few days if the error still occurs.

**Comment by eikowagenknecht** [comment]
174 entries in the last two days:

```
Logger: homeassistant
Source: custom_components/miele/binary_sensor.py:96
Integration: Miele@home ([documentation](https://github.com/HomeAssistant-Mods/home-assistant-miele), [issues](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues))
First occurred: 17. April 2022, 15:28:57 (174 occurrences)
Last logged: 00:19:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/miele/binary_sensor.py", line 96, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'
```

**Comment by baferdi** [comment]
Logger: homeassistant
Source: custom_components/miele/binary_sensor.py:101
Integration: Miele@home (documentation, issues)
First occurred: 29. Mai 2022, 03:11:45 (1615 occurrences)
Last logged: 14:47:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 209, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/miele/binary_sensor.py", line 101, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'

**Comment by the-ress** [comment]
I was getting errors like these when I had one of the `miele.*` entities disabled.
