### ISSUE TITLE
Error during setup of component miele

### ISSUE THREAD

**Issue by geni0602** [HomeAssistant-Mods/home-assistant-miele#95]
I get the following error after update to 0.9.1.

Any help? 
thx

Logger: homeassistant.setup
Source: custom_components/miele/miele_at_home.py:52
Integration: miele (documentation, issues)
First occurred: 18:01:46 (1 occurrences)
Last logged: 18:01:46

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 150, in async_setup
    data_get_devices = await client.get_devices(lang)
  File "/config/custom_components/miele/miele_at_home.py", line 52, in get_devices
    for home_device in home_devices:
TypeError: 'coroutine' object is not iterable

**Comment by geni0602** [comment]
I've done today a clean installation incl. new secret and id again. The integration started, I was able to make the authorization at Miele and now everything is working.

Before installation I deleted the old token located in config/.storage
