### ISSUE TITLE
[0.91] Error executing service

### ISSUE THREAD

**Issue by mamoel666** [HomeAssistant-Mods/home-assistant-miele#99]
Since today I get this error in the logs:

```
2022-01-27 17:03:43 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall configurator.configure (c:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx): configure_id=xxxxxxxxxxxxxxx-x, fields=>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 226, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/miele/__init__.py", line 86, in miele_configuration_callback
    await async_setup(hass, config)
  File "/config/custom_components/miele/__init__.py", line 151, in async_setup
    hass.data[DOMAIN][DATA_DEVICES] = _to_dict(data_get_devices)
  File "/config/custom_components/miele/__init__.py", line 108, in _to_dict
    for item in items:
TypeError: 'NoneType' object is not iterable
```
I already deleted the custom component, redownloaded, deleted the token cache, reauthorized (which is successful), tried v0.92b but nothing helps.

I'm running HA 2021.12.10 (Core) in Docker on a Intel NUC (Ubuntu 20.04.3 LTS).

**Comment by rborkow** [comment]
EDIT: The same query to `/v1/devices` is throwing a 504 Gateway Timeout in the Miele Swagger as well - something's up on Miele's end.

I've started seeing similar errors this morning as well, around the same time as a bunch of connection-related errors started showing up in the logs:

```
2022-01-27 05:34:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/lib/python3.9/site-packages/homeassistant/components/binary_sensor/__init__.py", line 205, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalInfo'
2022-01-27 05:34:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/lib/python3.9/site-packages/homeassistant/components/binary_sensor/__init__.py", line 205, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/miele/binary_sensor.py", line 88, in is_on
    return bool(self._device["state"][self._key])
KeyError: 'signalFailure'

...

2022-01-27 06:30:06 ERROR (MainThread) [custom_components.miele.miele_at_home] Failed to retrieve Miele devices: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2022-01-27 06:30:11 ERROR (MainThread) [custom_components.miele.miele_at_home] Failed to retrieve Miele devices: HTTPSConnectionPool(host='api.mcs3.miele.com', port=443): Max retries exceeded with url: /v1/devices?language=en (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

2022-01-27 06:31:52 WARNING (SyncWorker_16) [urllib3.connectionpool] Connection pool is full, discarding connection: api.mcs3.miele.com
```

Maybe an issue on Miele's side, or a change to the API?

**Comment by mamoel666** [comment]
Must have been an issue at Mieles side. My problem was fixed automatically. All problems gone.
